env:
  browser: true
  es2021: true
  jest: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:@typescript-eslint/recommended'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
  sourceType: module
  project: ./tsconfig.json

plugins:
  - react
  - deprecation
  - '@typescript-eslint'

rules:
  indent: [ 'off', 2 ]
  linebreak-style: [ 'error', 'unix' ]
  quotes: [ 'warn', 'single' ]
  semi: [ 'warn', 'always' ]
  semi-spacing: [ 'warn', { before: false, after: true } ]
  block-spacing: [ 'warn', 'always' ]
  '@typescript-eslint/no-extra-non-null-assertion': [ 'warn' ]
  deprecation/deprecation: 'warn'